import postgres from 'postgres';
import { readdir, readFile } from 'node:fs/promises';
import { extname, basename } from 'node:path';
import mammoth from 'mammoth';
import { PDFParse } from 'pdf-parse';
import OpenAI from 'openai';

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required. Run the migration first.');
const sql = postgres(process.env.DATABASE_URL, { max: 1 });
const slugify = (value) => value.trim().replace(/[\s_]+/g, '-').replace(/[^\p{L}\p{N}:.~-]/gu, '').replace(/-+/g, '-').toLowerCase();
const blocked = (text) => /\bconfidential\b|대외비|기밀|급여|연봉|\b(?:salary|payroll)\b|\b\d{6}-[1-4]\d{6}\b|[\w.+-]+@[\w.-]+\.[a-z]{2,}/iu.test(text);
const core = [
	['Wiki Viki:Basic Policy','# Basic Policy\n\nWiki Viki stores shared operational knowledge. Write verifiable information, protect private data, and improve pages collaboratively.\n\n## Core principles\n\n* Use anonymous editor handles.\n* Do not publish personal or restricted information.\n* Discuss contested edits before reverting them.'],
	['Wiki Viki:Editing Guidelines','# Editing Guidelines\n\n## Style\n\nUse clear headings, concise sentences, and [[Wiki Viki:Basic Policy|wiki links]] for related concepts. Add sources where available.[^1]\n\n## Syntax\n\n| Markup | Result |\n| --- | --- |\n| `[[Page]]` | Wiki link |\n| `~~text~~` | ~~Strike~~ |\n\n[^1]: Drafts generated by AI require human review.'],
	['Wiki Viki:Discussion','# Discussion\n\nUse each document’s **Discussion** tab to propose changes, record disagreements, and reach consensus.'],
	['Wiki Viki:Help','# Help\n\n## Find a document\n\nUse the search field in the navigation bar. A red link points to a page that does not exist yet.\n\n## Create and edit\n\nFollow a red link or choose **Edit** on an existing page. Every save creates a revision.'],
	['Wiki Viki:Recent Changes','# Recent Changes\n\nThis system records every document update. Use the sidebar and document history to inspect recent work.']
];

async function upsert(title, content) {
	const [doc] = await sql`INSERT INTO documents (slug,title,content,editor_handle) VALUES (${slugify(title)},${title},${content},'Operator-A') ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,content=EXCLUDED.content,updated_at=NOW() RETURNING *`;
	await sql`INSERT INTO revisions (document_id,content,editor_handle,summary) VALUES (${doc.id},${content},'Operator-A','Initial seed')`;
}

async function parse(path, ext) {
	const data = await readFile(path);
	if (ext === '.docx') return (await mammoth.extractRawText({ buffer: data })).value;
	const parser = new PDFParse({ data }); try { return (await parser.getText()).text; } finally { await parser.destroy(); }
}

async function structure(text, name) {
	if (!process.env.OPENAI_API_KEY) return { title: basename(name, extname(name)), sections: [{ heading: 'Overview', content: text }], aliases: [] };
	const ai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
	const response = await ai.responses.create({ model: process.env.OPENAI_MODEL || 'gpt-5-mini', input: `Rewrite only this source as an internal wiki draft without adding facts. Return JSON with title, sections[{heading,content}], aliases[].\n\n${text}` });
	return JSON.parse(response.output_text);
}

try {
	for (const [title, content] of core) await upsert(title, content);
	await sql`INSERT INTO announcements (title,body) SELECT 'Welcome to Wiki Viki','Read the Basic Policy before contributing.' WHERE NOT EXISTS (SELECT 1 FROM announcements WHERE title='Welcome to Wiki Viki')`;
	let files = []; try { files = (await readdir(new URL('../seed-data/', import.meta.url))).filter((name) => ['.docx','.pdf'].includes(extname(name).toLowerCase())); } catch {}
	for (const file of files) {
		try { const text = await parse(new URL(`../seed-data/${file}`, import.meta.url), extname(file).toLowerCase()); const result = await structure(text, file); const content = result.sections.map((s) => `## ${s.heading}\n\n${s.content}`).join('\n\n'); const status = blocked(text) ? 'blocked' : 'review'; await sql`INSERT INTO drafts (title,slug,content,source_name,aliases,governance,status,editor_handle) VALUES (${result.title},${slugify(result.title)},${content},${file},${sql.json(result.aliases || [])},${sql.json({ passed: status === 'review', seed: true })},${status},'Operator-A')`; console.log(`Drafted ${file}`); }
		catch (error) { console.error(`Failed ${file}: ${error.message}`); }
	}
	console.log(`Seeded ${core.length} core documents and processed ${files.length} source files.`);
} finally { await sql.end(); }

